services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U username -d mydb"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pg_data: